### ISSUE TITLE
Uncaught Error: premature end of char-class

### ISSUE THREAD

**Issue by mikelittman** [digitalfiz/language-lsl#13]
On a clean install, after installing the language-lsl package and attempting to set the Syntax selection to LSL I receive that error. 

OS: Windows 7
Atom Version: 1.4.3

Stack Trace:

```
Error: premature end of char-class
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\first-mate\lib\grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\src\tokenized-buffer.js:551:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\src\tokenized-buffer.js:537:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (<user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\src\tokenized-buffer.js:297:43)
    at <user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\src\tokenized-buffer.js:274:26
    at <user_path>\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:666:47
```

**Comment by furroy** [comment]
Just got Atom to try this package out and getting the same error.  Win 10, Atom 1.5.3

**Comment by digitalfiz** [comment]
Hey guys I looked at this last week and I can't figure out what's wrong with the cson. I am going to try again this weekend and see if i can do some conversion to the much less crappy json and see if i can figure out what's wrong.

**Comment by DakotaWolfi** [comment]
hi i post the comment here again :)
i think i try to upload the old version on my page :) then my version is working
i had the same problem with the new version
this is version 2.0.3 it should work
[language-lsl.zip](https://github.com/digitalfiz/language-lsl/files/209735/language-lsl.zip)

**Comment by mikelittman** [comment]
@digitalfiz Any progress?

**Comment by digitalfiz** [comment]
This should be fixed now. Forced myself to sit down and check every fricken line of the lsl.cson :P This is why you don't commit style changes with actual changes. The PR from @buildersbrewery shows almost the entire file modified so its was not easy figuring out what was wrong.

Oh I hate cson btw almost as much as I hate CoffeeScript ;-)
